# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b6f52d91bba4918369afcb075b40155c085207887431bbbc3bb47b013b2f62d10397bc03fdd412b56a3129dfd785df17ce03496d8cb8497e3f0c1989166d965c

test:
  secret_key_base: b675339fcbbe66988a6ad711821f352a82972e1f0bf20e902329433bb2c9b3b68c36edf6588939d8ce1bfd79e7b710df312eee82ba98c7ef5a25f4fc45353f2d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
